extends: ["spectral:oas", "spectral:asyncapi"]
rules:
  info-contact: warn
  info-description: warn
  info-license: warn
  license-url: off
  no-$ref-siblings: warn
  oas3-api-servers: warn
  oas3-examples-value-or-externalValue: warn
  oas3-operation-security-defined: off
  oas3-server-not-example.com: error
  oas3-unused-component: warn
  oas3-valid-media-example: warn
  oas3-valid-schema-example: warn
  openapi-tags: warn
  operation-description: warn
  operation-operationId: error
  operation-operationId-unique: error
  operation-operationId-valid-in-url: error
  operation-parameters: warn
  operation-success-response: error
  operation-tags: error
  operation-tag-defined: error
  path-declarations-must-exist: error
  path-keys-no-trailing-slash: error
  path-not-include-query: error
  path-params: error
  typed-enum: warn
