#!/bin/bash

# Burst Mode Feature Demonstration
# This script shows example usage of the burst mode feature

echo "=================================="
echo "Burst Mode Feature - Usage Examples"
echo "=================================="
echo ""

echo "1. Basic burst mode (with default 1 FPS rate limiting):"
echo "   ./object_detection --enable-burst-mode"
echo ""

echo "2. Energy-efficient monitoring with burst mode:"
echo "   ./object_detection --enable-burst-mode --analysis-rate-limit 1 --min-confidence 0.6"
echo ""

echo "3. Burst mode with viewfinder for debugging:"
echo "   ./object_detection --enable-burst-mode --show-preview --verbose"
echo ""

echo "4. Burst mode with network streaming:"
echo "   ./object_detection --enable-burst-mode --enable-streaming --streaming-port 8080"
echo ""

echo "5. Production deployment with burst mode:"
echo "   ./object_detection \\"
echo "     --enable-burst-mode \\"
echo "     --analysis-rate-limit 1 \\"
echo "     --min-confidence 0.6 \\"
echo "     --log-file /var/log/object_detection.log \\"
echo "     --heartbeat-interval 10"
echo ""

echo "=================================="
echo "Expected Behavior"
echo "=================================="
echo ""
echo "When burst mode is ENABLED:"
echo "  - At startup, you'll see: 'Burst mode: ENABLED - will max out FPS when new objects enter the scene'"
echo "  - When idle (no objects): Normal rate limiting applies (e.g., 1 FPS)"
echo "  - When NEW object enters: 'Burst mode ACTIVATED - new object type detected'"
echo "  - During burst: Frames analyzed as fast as possible (~5-30 FPS depending on hardware)"
echo "  - When objects stationary: 'Burst mode DEACTIVATED - all objects stationary'"
echo "  - When objects leave: 'Burst mode DEACTIVATED - no objects detected'"
echo ""

echo "Logs to watch for:"
echo "  [INFO] Burst mode: ENABLED - will max out FPS when new objects enter the scene"
echo "  [INFO] Burst mode ACTIVATED - new object type detected"
echo "  [DEBUG] Burst mode active: skipping normal rate limiting (minimal 1ms delay)"
echo "  [INFO] Burst mode DEACTIVATED - all objects stationary"
echo "  [INFO] Burst mode DEACTIVATED - no objects detected"
echo ""

echo "=================================="
echo "Testing Instructions"
echo "=================================="
echo ""
echo "To manually test burst mode:"
echo "  1. Start application with burst mode and verbose logging:"
echo "     ./object_detection --enable-burst-mode --verbose"
echo ""
echo "  2. Position yourself out of camera view initially"
echo ""
echo "  3. Walk into view → Watch for 'Burst mode ACTIVATED' in logs"
echo ""
echo "  4. Stand still for a few seconds → Watch for 'Burst mode DEACTIVATED - all objects stationary'"
echo ""
echo "  5. Walk out of view → Watch for 'Burst mode DEACTIVATED - no objects detected'"
echo ""
echo "  6. Repeat to verify state transitions work correctly"
echo ""
