#!/bin/bash
# Example script showing different stationary timeout configurations

echo "=== Stationary Object Detection Examples ==="
echo ""

echo "Example 1: Quick timeout (30 seconds) - for testing"
echo "Command: ./object_detection --stationary-timeout 30 --verbose"
echo "Effect: Photos stop after 30 seconds of no movement"
echo ""

echo "Example 2: Standard timeout (2 minutes / 120 seconds) - default"
echo "Command: ./object_detection"
echo "Effect: Photos stop after 2 minutes of no movement"
echo ""

echo "Example 3: Extended timeout (5 minutes / 300 seconds) - for slower scenes"
echo "Command: ./object_detection --stationary-timeout 300"
echo "Effect: Photos stop after 5 minutes of no movement"
echo ""

echo "Example 4: Long timeout (30 minutes / 1800 seconds) - for very slow scenes"
echo "Command: ./object_detection --stationary-timeout 1800"
echo "Effect: Photos stop after 30 minutes of no movement"
echo ""

echo "Example 5: Disable stationary detection (set very high timeout)"
echo "Command: ./object_detection --stationary-timeout 86400"
echo "Effect: Photos continue for 24 hours before stopping (effectively disabled)"
echo ""

echo "=== Disk Space Savings Examples ==="
echo ""
echo "Scenario: Security camera monitoring a parking lot"
echo "Without stationary detection:"
echo "  - 360 photos/hour (every 10 seconds)"
echo "  - ~72 MB/hour (~1.7 GB/day)"
echo ""
echo "With stationary detection (120s timeout):"
echo "  - 12 photos when car parks"
echo "  - 0 photos while car remains parked"
echo "  - ~2.4 MB when car parks"
echo "  - Savings: ~97-99% disk space"
echo ""

echo "=== Recommended Settings ==="
echo ""
echo "Use Case: Home Security"
echo "  Timeout: 120-300 seconds (2-5 minutes)"
echo "  Rationale: Capture arrival, reduce redundant photos"
echo ""
echo "Use Case: Wildlife Monitoring"
echo "  Timeout: 60-120 seconds (1-2 minutes)"
echo "  Rationale: Animals may be still but present, shorter timeout captures more"
echo ""
echo "Use Case: Parking Lot Monitoring"
echo "  Timeout: 300-600 seconds (5-10 minutes)"
echo "  Rationale: Vehicles rarely move, longer timeout saves disk space"
echo ""
echo "Use Case: Traffic Monitoring"
echo "  Timeout: 30-60 seconds"
echo "  Rationale: Vehicles at traffic lights, capture state changes quickly"
echo ""
