#!/usr/bin/env bash
# <Script Name>
# <Description what this module does>
# Written by <Author>
# GPL V3
########


# Source error handling, leave this in place
set -x
set -e

source /common.sh
install_cleanup_trap

sudo apt-get update
sudo apt-get install -y htop screen git python-smbus i2c-tools hostapd dnsmasq
git clone https://github.com/ingojaeckel/go-raspberry-pi-timelapse.git

unpack /filesystem/home/pi /home/"${BASE_USER}" "${BASE_USER}"
unpack /filesystem/home/root /root root
unpack /filesystem/boot /boot

# Unpack root at the end, so files are modified before
unpack /filesystem/root /

sudo chmod 644 /lib/systemd/system/timelapse.service
sudo systemctl enable timelapse.service
