name: Build for Pi/Arm
on:
  push:
    paths:
      - 'admin/**'
      - 'conf/**'
      - 'files/**'
      - 'frontend/**'
      - 'rest/**'
      - 'timelapse/**'
      - 'main.go'
      - 'go.*'
      - '.github/workflows/go-arm.yml'
  pull_request:
    paths:
      - 'admin/**'
      - 'conf/**'
      - 'files/**'
      - 'frontend/**'
      - 'rest/**'
      - 'timelapse/**'
      - 'main.go'
      - 'go.*'
      - '.github/workflows/go-arm.yml'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
    - name: Build frontend
      run: cd frontend && npm install && npm run build && cd ../
    - uses: actions/setup-go@v5
      with:
        go-version: 1.24.x
      id: go
    - name: Vet
      run: ./build-for-pi.sh
