name: Build for Pi/Arm
on:
  push:
    paths:
      - 'admin/**'
      - 'conf/**'
      - 'files/**'
      - 'frontend/**'
      - 'rest/**'
      - 'timelapse/**'
      - 'main.go'
      - 'go.*'
      - '.github/workflows/go-arm.yml'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
    - name: Install frontend dependencies
      run: cd frontend && npm install
    - name: Run frontend tests
      run: cd frontend && npm run test && cd ../
    - name: Install Playwright browsers
      run: cd frontend && npx playwright install --with-deps chromium
    - name: Run Playwright E2E tests
      run: cd frontend && npm run test:e2e
    - name: Upload Playwright test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-arm
        path: frontend/playwright-report/
        retention-days: 7
    - name: Build frontend
      run: cd frontend && npm run build && cd ../
    - uses: actions/setup-go@v5
      with:
        go-version: 1.25.2
      id: go
    - name: Vet
      run: ./build-for-pi.sh
