name: Build for Pi/Arm
on:
  push:
    paths:
      - 'admin/**'
      - 'conf/**'
      - 'files/**'
      - 'rest/**'
      - 'timelapse/**'
      - 'main.go'
      - 'go.*'
      - '.github/workflows/go-arm.yml'
  pull_request:
    paths:
      - 'admin/**'
      - 'conf/**'
      - 'files/**'
      - 'rest/**'
      - 'timelapse/**'
      - 'main.go'
      - 'go.*'
      - '.github/workflows/go-arm.yml'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Build frontend
      run: cd frontend && npm install && npm run build && cd ../
    - uses: actions/setup-go@v3
      with:
        go-version: 1.23.2
      id: go
    - name: Vet
      run: ./build-for-pi.sh
