name: Build
on:
  push:
    paths:
      - 'admin/**'
      - 'conf/**'
      - 'files/**'
      - 'frontend/**'
      - 'rest/**'
      - 'timelapse/**'
      - 'main.go'
      - 'go.*'
      - '.github/workflows/go.yml'
  pull_request:
    paths:
      - 'admin/**'
      - 'conf/**'
      - 'files/**'
      - 'frontend/**'
      - 'rest/**'
      - 'timelapse/**'
      - 'main.go'
      - 'go.*'
      - '.github/workflows/go.yml'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
    - name: Install frontend dependencies
      run: cd frontend && npm install
    - name: Run frontend tests with coverage
      run: |
        cd frontend
        npm test -- --coverage --watchAll=false > test-output.txt 2>&1 || true
        cat test-output.txt
        # Extract and display coverage summary
        echo ""
        echo "================================"
        echo "Frontend Test Coverage Summary:"
        echo "================================"
        grep -A 20 "File.*Stmts.*Branch.*Funcs.*Lines" test-output.txt || echo "Coverage summary not found"
        echo "================================"
    - name: Upload frontend coverage artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: frontend-coverage-report
        path: frontend/coverage/
        retention-days: 7
    - name: Build frontend
      run: cd frontend && npm run build && cd ../
    - uses: actions/setup-go@v5
      with:
        go-version: 1.24.x
      id: go
    - name: Vet
      run: go vet ./...
    - name: Test
      run: go test -v -cover ./...
    - name: Build
      run: go build -v .
