name: Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Build frontend
      run: cd frontend && npm install && npm run build && cd ../
    - name: Test frontend
      run: cd frontend && npm test -- --coverage --watchAll=false && cd ../
    - uses: actions/setup-go@v3
      with:
        go-version: 1.23.2
      id: go
    - name: Vet
      run: go vet ./...
    - name: Test
      run: go test -v -cover ./...
    - name: Build
      run: go build -v .
