name: Build
on:
  push:
    paths:
      - 'admin/**'
      - 'conf/**'
      - 'files/**'
      - 'frontend/**'
      - 'rest/**'
      - 'timelapse/**'
      - 'main.go'
      - 'go.*'
      - '.github/workflows/go.yml'
  pull_request:
    paths:
      - 'admin/**'
      - 'conf/**'
      - 'files/**'
      - 'frontend/**'
      - 'rest/**'
      - 'timelapse/**'
      - 'main.go'
      - 'go.*'
      - '.github/workflows/go.yml'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: Install frontend dependencies
      run: cd frontend && npm install && cd ../
    - name: Test frontend
      run: cd frontend && npm test -- --coverage --watchAll=false && cd ../
    - name: Display frontend coverage summary
      run: |
        cd frontend
        COVERAGE_PCT=$(grep -oP '"lines":\s*{[^}]*"pct":\s*\K[0-9.]+' coverage/coverage-summary.json | head -1)
        echo "### Frontend Test Coverage: ${COVERAGE_PCT}%" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Coverage details available in artifacts." >> $GITHUB_STEP_SUMMARY
        cd ../
    - name: Upload frontend coverage
      uses: actions/upload-artifact@v3
      with:
        name: frontend-coverage
        path: frontend/coverage/
        retention-days: 7
    - name: Build frontend
      run: cd frontend && npm install && npm run build && cd ../
    - uses: actions/setup-go@v5
      with:
        go-version: 1.24.x
      id: go
    - name: Vet
      run: go vet ./...
    - name: Test
      run: go test -v -cover ./...
    - name: Build
      run: go build -v .
