name: Build TypeScript and Go
on:
  push:
    paths:
      - 'admin/**'
      - 'conf/**'
      - 'files/**'
      - 'frontend/**'
      - 'rest/**'
      - 'timelapse/**'
      - 'main.go'
      - 'go.*'
      - '.github/workflows/go.yml'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
    - name: Frontend - dependencies
      run: cd frontend && npm install
    - name: Frontend - dependencies - playwright browsers
      run: cd frontend && npx playwright install --with-deps chromium
    - name: Frontend - tests
      run: cd frontend && npm run test && cd ../
    - name: Frontend - build for E2E (dev mode)
      run: cd frontend && npm run build -- --mode development && cd ../
    - name: Frontend - tests - playwright
      timeout-minutes: 3
      run: cd frontend && npm run test:e2e
    - name: Upload Playwright test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: frontend/playwright-report/
        retention-days: 7
    - name: Frontend - build for production
      run: cd frontend && npm run build && cd ../
    - uses: actions/setup-go@v5
      with:
        go-version: 1.25.2
      id: go
    - name: Go vet
      run: go vet ./...
    - name: Go test
      run: go test -v -cover ./...
    - name: Go build
      run: go build -v .
    - name: Build for Pi
      run: ./build-for-pi.sh